version: '3.8'

services:
  chatbot:
    build: ./chatbot
    ports:
      - "5000:5000"  
    depends_on:
      - calendar_service 

  calendar_service:
    build: ./calendar_service
    ports:
      - "5001:5001"  

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"    
